# Generated by Django 2.2.6 on 2019-10-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_profile_for', models.CharField(blank=True, choices=[('Self', 'Self'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Niece', 'Niece'), ('Nephew', 'Nephew'), ('Cousion', 'Cousion'), ('Friend', 'Friend')], max_length=8, null=True)),
                ('firstname', models.CharField(max_length=20)),
                ('middlename', models.CharField(blank=True, max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('contact', models.IntegerField()),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100, unique=True)),
                ('confirm', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
